logging:
  pattern:
    console: "[Kafka Consumer] %clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(---){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"

# setting default group-id for all consumer, and
#  if it is mentioned explicitly in the class it will override the properties for specific consumer
spring:
  kafka:
    consumer:
      group-id: default-spring-consumer
      auto-offset-reset: earliest
  server:
    port: 8081

